### PR TITLE
FeatureFor Blade Directive

### PR DESCRIPTION
**Pull request by victorlap**
Resubmission of #8.

## Description
I have added the `@featurefor` blade directive, to easily use the `isEnabledFor()` method.

## Motivation and context
This change is to complement the already existing `@feature` blade directive.

## How has this been tested?
I have test this the same way the laravel blade directives [are tested](https://github.com/laravel/framework/blob/5.6/tests/View/Blade/BladeIfAuthStatementsTest.php).

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

### CODE REVIEW

**Comment by francescomalatesta** [comment]
This is awesome :) just a question: what about adding support for the `php artisan feature:scan` command?

**Comment by victorlap** [comment]
Missed that one, will add that functioner tomorrow

**Comment by francescomalatesta** [comment]
Thank you :D looking forward to merge this one ;)

**Comment by victorlap** [comment]
I have altered the regex, and changed the foreach to make use of collections.

**Comment by francescomalatesta** [comment]
Sorry for the big late, I wasn't around for a while :( thanks for your precious contribution!

**Comment by Samboun01** [comment]
Great work

**Pull request merged**
